import { config } from "dotenv";
config();

const env = process.env;

export default Object.freeze({
    PORT: env.PORT,
    CLIENT_BASE_URL: env.CLIENT_BASE_URL,
    SERVER_BASE_URL: env.SERVER_BASE_URL,

    JWT_ACCESS_SECRET: env.JWT_ACCESS_SECRET,
    JWT_REFRESH_SECRET: env.JWT_REFRESH_SECRET,
    ACCESS_TOKEN_EXPIRY: env.ACCESS_TOKEN_EXPIRY,
    REFRESH_TOKEN_EXPIRY: env.REFRESH_TOKEN_EXPIRY,

    MAILTRAP_SMTP_HOST: env.MAILTRAP_SMTP_HOST,
    MAILTRAP_SMTP_USER: env.MAILTRAP_SMTP_USER,
    MAILTRAP_SMTP_PASS: env.MAILTRAP_SMTP_PASS,
    MAILTRAP_SMTP_PORT: env.MAILTRAP_SMTP_PORT,

    ADMIN_USERNAME: env.ADMIN_USERNAME,
    ADMIN_PASSWORD: env.ADMIN_PASSWORD,
    ADMIN_DISPLAY_NAME: env.ADMIN_DISPLAY_NAME,
    ADMIN_EMAIL: env.ADMIN_EMAIL,

    REDIS_URI: env.REDIS_URI,

    NODE_ENV: env.NODE_ENV,

})